// ─── ZZYSY PLANOS ────────────────────────────────────────────────
export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    priceLabel: "Grátis",
    period: "para sempre",
    description: "Para experimentar e explorar",
    users: 1,
    campaigns: 1,
    pieces: 500,
    highlighted: false,
    cta: "Começar grátis",
    features: [
      "1 usuário",
      "1 campanha ativa",
      "500 peças/mês",
      "Formatos padrão",
      "Exportar PNG e TIFF",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    price: 19,
    priceLabel: "R$ 19",
    period: "por mês",
    description: "Para freelancers e pequenos projetos",
    users: 1,
    campaigns: 4,
    pieces: 2000,
    highlighted: false,
    cta: "Assinar Starter",
    features: [
      "1 usuário",
      "4 campanhas ativas",
      "2.000 peças/mês",
      "Todos os formatos",
      "Exportar PNG e TIFF",
      "Suporte por e-mail",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 89,
    priceLabel: "R$ 89",
    period: "por mês",
    description: "Para agências e times criativos",
    users: 1,
    campaigns: 10,
    pieces: 5000,
    highlighted: true,
    cta: "Assinar Pro",
    features: [
      "1 usuário",
      "10 campanhas ativas",
      "5.000 peças/mês",
      "Todos os formatos",
      "Exportar PNG e TIFF (layers)",
      "Suporte prioritário",
      "Histórico de versões",
    ],
  },
  {
    id: "agency",
    name: "Agency",
    price: 399,
    priceLabel: "R$ 399",
    period: "por mês",
    description: "Para agências com múltiplos clientes",
    users: "5–10",
    campaigns: null,
    pieces: null,
    highlighted: false,
    cta: "Assinar Agency",
    features: [
      "5 a 10 usuários",
      "Campanhas ilimitadas",
      "Peças ilimitadas",
      "Todos os formatos",
      "Exportar PNG e TIFF (layers)",
      "Suporte dedicado",
      "Histórico de versões",
      "Relatórios de uso",
    ],
  },
];

export type Plan = typeof plans[0];
