name: Deploy to Vercel
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_ORG_ID: team_2NIdc5s6ybzcTI5Cp8FkM4tP
          VERCEL_PROJECT_ID: prj_aVpnD700zr4nYZH9U0ZDJXJ54G8b
